### ISSUE TITLE
@rpath issue still appear on OSX

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/swigcsm#16]
Even after merging #15, it appears that rpath issues are still occurring on OSX. Using the latest anaconda upload on OSX (py3.6), I am seeing the following. If I build locally, it looks like everything is good. Therefore, I suspect that the issue has something to do with the conda build and the relocatability of the package. Specifically, [this](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#relocation)

@Kelvinrr Do you have any thoughts on this?

```bash
ImportError: dlopen(/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/_csmapi.so, 2): Library not loaded: @rpath/libcsmapi.dylib.3.0.3
  Referenced from: /Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/_csmapi.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/__init__.py", line 1, in <module>
    from csmapi.csmapi import *
  File "/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/csmapi.py", line 17, in <module>
    _csmapi = swig_import_helper()
  File "/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/csmapi.py", line 16, in swig_import_helper
    return importlib.import_module('_csmapi')
  File "/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_csmapi'
>>>
(autocnet) igswzawglt-jlra:github jlaura$ ls /Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/
__init__.py	__pycache__	_csmapi.so	csmapi.py
(autocnet) igswzawglt-jlra:github jlaura$ otool -L /Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/_csmapi.so
/Users/jlaura/miniconda3/envs/autocnet/lib/python3.6/site-packages/csmapi/_csmapi.so:
	@rpath/libcsmapi.dylib.3.0.3 (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libpython3.6m.dylib (compatibility version 3.6.0, current version 3.6.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

**Comment by jlaura** [comment]
Also, @acpaquette @Kelvinrr can you all reproduce on your Macs?

**Comment by jlaura** [comment]
So, the error should not be a surprise. [The build logs](https://travis-ci.org/USGS-Astrogeology/swigcsm/jobs/507692902#L754) looked like the binary prefix was not being detected properly.  I just tried a completely fresh env and success:

```bash
Python 3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 05:40:40)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csmapi
>>> dir(csmapi)
['ADJUSTABLE', 'CSM_GEOMETRIC_MODEL_FAMILY', 'EcefCoord', 'EcefCoordCovar', 'EcefCoordCovar_swigregister', 'EcefCoord_swigregister', 'EcefLocus', 'EcefLocus_swigregister', 'EcefVector', 'EcefVector_swigregister', 'Ellipsoid', 'Ellipsoid_swigregister', 'FICTITIOUS', 'FIXED', 'GeometricModel', 'GeometricModel_swigregister', 'ImageCoord', 'ImageCoordCovar', 'ImageCoordCovar_swigregister', 'ImageCoord_swigregister', 'ImageVector', 'ImageVector_swigregister', 'Isd', 'Isd_swigregister', 'Model', 'Model_swigregister', 'NONE', 'NON_ADJUSTABLE', 'Plugin', 'PluginList', 'PluginList_swigregister', 'Plugin_findPlugin', 'Plugin_getDataDirectory', 'Plugin_getList', 'Plugin_removePlugin', 'Plugin_setDataDirectory', 'Plugin_swigregister', 'REAL', 'RasterGM', 'RasterGM_swigregister', 'SharingCriteria', 'SharingCriteria_swigregister', 'SwigPyIterator', 'SwigPyIterator_swigregister', 'VALID', 'Version', 'Version_swigregister', 'Warning', 'WarningList', 'WarningList_swigregister', 'Warning_swigregister', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_csmapi', 'csmapi']
>>>```

I am going to leave this open for a bit to see if anyone else is able to reproduce.

**Comment by Kelvinrr** [comment]
The most recent build from conda seems to work. Is that from Travis build or your local build? I remember previous versions had `otool -l` print out a rpath that only exists inside the Travis env.

**Comment by jlaura** [comment]
I think that my py3.6 env must be pulling a cached (or local) build even after `conda clean --all`. I am going to close. Thanks!
